services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - PRIVATE_KEY=kjefw373784
language: node_js
node_js:
  - "10"
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'drop database if exists bookapp_test;' -U postgres
  - psql -c 'create database bookapp_test;' -U postgres
  - npm run db-migrate:test
script:
  - npm test
after_success:
  - npm run coveralls
